
export default function AboutT() {
  return (
    <section>
        <h1 className="text-center">ABOUT NEVADA TURQUOISE</h1>
        <h2>A Little History of Nevada Turquoise</h2>
        <p> Native American peoples first mined the beautiful Turquoise of Nevada long before the first European explorers entered the area. Some of the mines such as the Fox and Crescent Peak deposits were worked extensively. For centuries going back to the times of the Anasazi, the native peoples of Nevada produced beautiful necklaces and other decorative and sacred items using turquoise. However, unlike some of the tribes in Arizona that also cherish turquoise, silver work and the art of making Native American style silver jewelry never became fully established in Nevada. As a result, even though Nevada still produces considerable quantities of turquoise, the traditional use of this gem in the crafts of the Paiute and Shoeshone tribes of Nevada is rare by comparison to the prolific use of these gems by the Arizona tribes. This also explains why, although there are well-known styles for the turquoise jewelry work of the Navajo, Zuni and other Arizona tribes, no similar well-established style exists for the Paiute or Shoeshone peoples of Nevada.</p>
        <p>The first Nevada turquoise discovery made by prospectors of European decent was made near Columbus in the early 1870s. At that time, it was only the second turquoise deposit in the US known to European miners. When Turquoise became fashionable during the period 1908 – 1910, the high prices attracted the attention of local prospectors and a number of new Nevada turquoise discoveries were made. Most of the turquoise discoveries made at that time were located in the Esmerelda/Mineral/Nye counties area which is the part of Nevada located nearest to that first 1870s discovery. By the late 1920’s and 1930’s turquoise once more came back into vogue, and increased prices again led to a number of new discoveries, and this time most of the new finds were located in Lander County, farther to the north. In the 1960s and 1970s, increased turquoise prices again led to new discoveries and production at mines all across Nevada, most notably the deposits at Carico Lake. Nevada has been a major producer of turquoise since the 1920s, and until the early 1980&apos;s, the State was the largest producer in the US. In this era of small turquoise operations, it may again be the largest producer. It is estimated that over the years, more than 100 different mines and prospects located in Nevada have produced significant quantities of turquoise, much of it of very good to excellent quality. That number far exceeds the total number of turquoise deposits all in the rest of the US combined. Production from these mines varied from a few thousand dollars worth of material at some of the smaller properties to many millions of dollars at the more productive ones. To date, the total value of the rough turquoise from the state of Nevada is estimated to comfortably exceed $250 million dollars. </p>
        <p>In recent years, the small central Nevada town of Austin has sort of become the unofficial turquoise capital of Nevada. This is because of its location close to several turquoise mining districts that are still producing some material. These include the Damale/Godber, Carico Lake, McGuinness, and Blue Diamond/Papoose areas. Even though the town has less than a thousand residents, it has three nice shops that specialize in fine Nevada turquoise jewelry. Both rough and cut stones are available as well.</p>


        <h2>The Qualities of Nevada Turquoise</h2>
        <p> Nevada produces some of the finest turquoise in the world, and probably the planet&apos;s widest diversity of colors and mixes of matrix patterns. Turquoise from Nevada comes in various shades of blue, blue-green, green-blue, and green, all of which are considered valuable. Nevada produces some unique shades of bright mint to apple to neon yellow green that are unequalled anywhere else on earth. Some of this unusual turquoise may contain significant zinc and iron, which is the cause of the beautiful bright green to yellow-green shades.</p>
        <p>Nevada turquoise can be solid colored without any host matrix (sometimes called clear) or spider webbed with brown, black, red or golden webbing; the spider webbing may occur in any of the different colors or shades. Other forms of turquoise and matrix stones also occur. Some of the clear blue material is considered among the finest pure-blue turquoise produced. It can occur in thin seam-like veins or as nodules (nuggets), with single nodules reported as large as 150 pounds. Though a considerable portion of Nevada turquoise is of very high quality, it does vary from hard solid material that takes a good polish, to soft porous material that can only be used after it has been treated by an enhancement, or stabilization processes.</p>
        <p>Associated with some of the turquoise deposits are three other gem materials that can resemble certain colors and shades of turquoise, but are technically separate mineral species. These include Variscite, Chalcosiderite and Faustite. Chalcosiderite and Faustite are considered as belonging to the &quot;turquoise family&quot; of minerals, and are often sold as turquoise because the different types commonly occur in the same deposit and it is not possible to clearly distinguish between these gems simply by looking at the color of the stone. Since the gem owner does not wish to destroy the gem to chemically analyze it and find out exactly what he had, the fact that these gemstones are all members of the &quot;turquoise family&quot; of minerals is usually considered acceptable. All are commonly marketed as turquoise, with Variscite sometimes being sold as &quot;variquoise&quot;. Attractive and beautiful gem stones can be cut from any of them. Faustite is a Nevada mineral, and was first identified at the Copper King Mine in the Maggie Creek area of Elko County in 1954.</p>


        <h2>What It Takes to Mine Nevada Turquoise</h2>
        <p> The western part of the United States produces some excellent quality gem turquoise. Essentially all of U.S. turquoise now being mined comes from the states of Nevada, Arizona, Colorado, and New Mexico.  Nevada has been a leading producer of turquoise for many years, and there are a large number of deposits within the state. For a number of reasons, all of the current turquoise mining operations here in the US are done on a small scale, and large quantities cannot be produced. The demand for high quality southwestern turquoise is far greater than these small mines can supply, and because the U.S. mines do not produce enough gem material to meet the country&apos;s market demands, turquoise from other parts of the world, particularly Tibet, is often used by Native Americans and other jewelry artists to make their jewelry. This strong demand and low production for high quality American turquoise explains the high price of this highly desired material.</p>
        <p>Turquoise deposits, with a few exceptions, are not very large and often productive mines yield well for only a few months or years after which the deposits become depleted, as the vein pinches out or the pocket is exhausted. The mine owner must then search the property for additional deposits. If additional turquoise is not found quickly, years may pass while the mine lies unworked. Then, if a new owner buys or leases the claim and reactivates the workings, there is no guarantee that the new work will be successful. </p>
        <p>Historically, Nevada turquoise mining has always been done on a small scale operation, as the labor intensive and time consuming process of extracting turquoise from its mother rock just does not lend itself well to large scale operations. Even Nevada&apos;s best known turquoise miners of the past, like Lee Hand, or the members of the Edgar family, were small scale operators who enjoyed the hunt for the precious blue gem. As in the past, most turquoise mining operations today are very small, some as small as one family working the site for only a few weeks per year. Most of the mining sites are very isolated, and living and working conditions are primitive - often the nearest drinkable water is many miles away from the mine. Heavy equipment such as backhoes, bulldozers or the compressors and drills used in blasting hard rock formations are expensive to purchase and operate. It is difficult to justify such expenses for these small-scale, part time turquoise operations. Unlike modern gold mining, where a few employees can mine and process thousands of tons of rock each day, turquoise mining requires a &quot;hands on&quot; approach. Gem material must be slowly and carefully removed from its mother rock or it will be destroyed in the extraction process. This is the major reason the gem quality turquoise deposits of Nevada are not worked more extensively - because the cost of labor in the US is expensive. High turquoise prices and strong demand are required to justify the expense of working a turquoise mine on a true &quot;full time&quot; commercial basis.</p>
        <p>One advantage modern miners have over the &quot;old time&quot; prospectors, who worked with hand tools, is larger equipment like backhoes and bulldozers which allow barren overburden to be easily removed. Initiating a larger-scale mining operation for turquoise today requires an immense amount of capital and the expenses of purchasing  equipment and other essential items can run into the millions of dollars. Due to environmental regulations, reclamation bonds are required to be put up that will guarantee that the surrounding area will be returned to its natural state when the mining operation is finished. It can become so complicated and costly (with no guarantee of return) that few people are willing to take on the risks of mining for turquoise on a large scale today. As a result, the operations remain small. For the operators who continue to work, it is essentially a labor of love - and not really much of a scheme for making big money. </p>


        <h2>About the Geology of Nevada Turquoise</h2>
        <p> On a worldwide basis, turquoise in not a very common mineral. Formation of turquoise requires five specific conditions: the presence of three chemicals: 1) Copper, 2) Aluminum, and 3) Phosphate. In addition, it also requires two environmental conditions - 4) Voids in the rock for the turquoise to form in, and the final thing is 5) An arid environment. This is just because of the way turquoise forms - too much running water simply washes away the solutions that could form the turquoise. To have all these conditions occur in the same place is a bit unusual - which is why turquoise is so rare.</p>
        <p>This unusual combination of geologic conditions has come together to form high quality turquoise at many places in Nevada. Regional thrust faulting in Nevada has caused widespread fracturing of the local rocks which has resulted the formation of the necessary voids. By a lucky coincidence, it turns out that the sedimentary rocks which were broken in this process just happened to be high in Aluminum and Phosphate. The mountain building processes which caused the faulting and fracturing, also introduced widespread low grade copper mineralization. Together with Nevada&apos;s generally arid environment and sufficient amounts of time, these conditions have led to the formation of world-class turquoise deposits. The mountain building processes have also caused silicification (the introduction of silica or quartz into the rock), which is why such a high percentage of Nevada turquoise is so hard and of a true gem quality. However, in many places those same geologic systems that caused the formation of turquoise also introduced gold mineralization into the same types of rocks. Other types of mineral deposits such as barite were also created as well. This leads to a situation where it is fairly common to find gold deposits in or around the general neighborhood of turquoise mines in Nevada.  This is also the reason why many old Nevada turquoise properties have been acquired and explored by various gold mining companies.</p>
        <p> The formation of these unusual gold deposits have been a huge economic boon to the state of Nevada, but it also has unfortunately led to a number of turquoise properties being mined out as gold mines or potential turquoise properties otherwise being tied up by gold mining companies. Barite mining operations have also led to the destruction of several previously productive turquoise properties. The net result of this situation is that it further limits the amount of high quality Nevada turquoise available in the US market.</p>
        <p>Most of the turquoise deposits in Nevada occur along a wide belt of tectonic activity that coincides with the state&apos;s zone of thrust faulting. It strikes about N15E and extends from the northern part of Elko County, southward down to the California border west of Tonopah. The principal producing turquoise mines have been located in the Nevada Counties that lie along this geologic trend - especially Esmerelda and Lander Counties. We have turquoise mines in both of these two very productive counties. </p>
    </section>
  )
}
